### ISSUE TITLE
Gov - Reforms

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-3-Cold-War-Era-Mod-CWE#2]
**Political System**

FUNDAMENTAL PRINCIPLES OF THE STATE

Governance Structure (V)
- Monarchy
- Pres Republic
- Semi Pres Republic
- Parl Republic
- Council Republic
- Theocracy

[Note: Leader to be renamed to Chief Executive for republics if THIS is an SAR or Devolved State subject type. For Colonial Puppets, the Leader is to be the overlord's ruler.]

Constitutional Principles
- Parliamentary Supremacy
- Constitutional Supremacy

State Centralisation (V)
- Unitary State
- Federal State

Secession Rights
- No Secession Allowed
- Secession Allowed

Diplomatic Status (V)
- Neutral
- Partial Neutrality
- Non-Neutral

RULER’S POWERS

Distribution of Power (V)
- Autocracy [For dictatorships]
- Oligarchy [For regimes]
- Democracy [For normal republics]

Leader’s Term Limit (CANCELLED)
- No Term Limit (Monarchy becomes elective without this)
- 6 years
- 5 years
- 4 years

PARLIAMENT’S POWERS

Legislature Structure (CANCELLED)
- Politiburo
- Unicameral
- Bicameral  

Legislature Members (CANCELLED)
- Appointed
- Semi Appointed
- Elected

Legislature Elections (CANCELLED)
- 6 years
- 5 years
- 2 years

JUDICIAL POWERS

Judicial System
- Fully Autochthonous
- Partially autochthonous
- Foreign Legal System (for colonies)

Judicial Members (V)
- Politicised
- Semi-Independent
- Independent

Legal System
- Civil Law
- Common Law

CIVIL SERVICE

Civil Service (V)
- Hereditary
- Appointed
- Elected

VOTER & POLITICAL PARTIES RIGHTS

Voting Registration (USE VANILLA)
- Biased towards Educated
- Biased towards Wealthy
- Biased towards Poor
- Unbiased Voting Registration

Voting Constituencies (USE VANILLA)
- Rigged
- Gerrymandered
- Fair

Voting Rights (USE VANILLA)
- Primary Cultures Only
- Accepted cultures Only
- Dependents Disallowed
- All Cultures Accepted

Political parties (USE VANILLA)
- None allowed
- Approved Parties only
- All allowed

Political Campaigning Rights (USE VANILLA)
- No campaigning allowed
- Limited campaigning allowed
- Unrestricted campaigning

**Citizen Rights**
Freedom of Speech (USE VANILLA)
- Dissent Outlawed
- Dissent Partially Tolerated
- Free Speech

Freedom of Assembly (USE VANILLA)
- No Right to Assemble
- Assembly Licence Required
- Unrestricted Assembly Rights

Freedom of Religion (USE VANILLA)
- No Religious Freedom
- Partial Religious Freedom
- Full Religious Freedom

Minority Rights (USE VANILLA)
- Minority Oppression
- Equal Rights
- Affirmative Action

Trade Union Rights
- No Trade Unions
- State Controlled Unions
- Restricted Trade Unions
- Unrestricted Trade Unions

Public Security (USE VANILLA)
- Draconian Policing
- Moderate Policing
- Gentle Policing

Slavery 
- Slave Trade
- Legacy Slavery
- Debt Slavery
- Political Slavery
- Slavery Banned

Gun Rights
- No Right to Bear Arms
- Limited Right to Bear Arms
- Unrestricted Right to Bear Arms

**Social Policies**
Health Care Institutions
- No State Healthcare
- Mixed
- Public

Education Institutions
- No State Schools
- Mixed
- Public

Education System
- Ideological
- Religious
- Secular

Population Control
- Anti-Growth
- None
- Pro-Growth

Welfare System
- None
- Private
- Mixed
- Public (Activates Pension, Unemployment and Public Housing institutions)

**Economic Policies**
Economic Policy
- Fully Planned
- Semi Planned
- State Capitalism
- Interventionism
- Laissez-faire

Trade Policy
- Import Substitution
- Balanced Trade Policy
- Export Economy

Monetary Policy
- Deflationary
- Neutral
- Expansionary

Company Ownership
- State Owned Only
- Private Ownership Allowed

Workers Rights
- Pro Company
- Balanced
- Pro Worker

Right to Work
- Men Only
- No Gender Restrictions

Financial Sector
- Heavily Regulated
- Moderately Regulated
- Lightly Regulated

**Military**

Military Political Rights
- Politicised
- Non-politicised

Military Structure (USE VANILLA)

Conscription (USE VANILLA)

Military Use (USE VANILLA)
- Defensive Actions only
- Special Military Operations
- Full War Rights

WMDs Use
- No WMD Allowed
- Nuclear Weapons Permitted
- Nuclear & Chemical Weapons Permitted
- Nuclear, Biological & Chemical Weapons Permitted

**Comment by ccfox** [comment]
I believe that Politburo is a party structure, and not a legislative structure. Tricameralism might be something to add, though it was so rare it was only used in three instances (Quite ironic) as far as I am aware; Yugoslavia's constituent states, the Republic of China (until 1949), and South Africa until the end of Apartheid.


For Legislature Elections, 4 and 3 would be good to add, for nations that have elections with those term lengths.

For Voting Registration, 'Restricted Franchise' for instances where the voting franchise, rather than simply being bias, is restricted to only certain castes or groups within the populace.

For Freedom of Religion, 'State Religion' as an absolute restriction on religion without implying atheism.

Political parties, I'd change 'None Allowed' to something like 'Ruling Party Only' or the like as to not have it get confused with Non-Partisan political systems in which parties do not exist (usually, irl, only used in cases of absolute monarchies where political parties don't exist because the monarch still appoints the legislature or autocratic states where there isn't a clear party for the ruler - though hypothetically part of several systems).
